// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBaiGiangAPI.Data;

#nullable disable

namespace WebBaiGiangAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBaiGiangAPI.Models.BaiGiang", b =>
                {
                    b.Property<string>("MaBaiGiang")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Chuong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenBaiGiang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaBaiGiang");

                    b.HasIndex("MaLop");

                    b.ToTable("BaiGiangs");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.BaiTap", b =>
                {
                    b.Property<string>("MaBaiTap")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FileBaiTap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("HanNop")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkBaiTap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaNguoiTao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenBaiTap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("MaBaiTap");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("BaiTaps");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.BangDiem", b =>
                {
                    b.Property<string>("MaBangDiem")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("ChuyenCan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HeSo1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HeSo2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("TBKT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThiLan1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ThiLan2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongKetLan1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongKetLan2")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaBangDiem");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("BangDiems");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.BoMon", b =>
                {
                    b.Property<string>("MaBoMon")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TenBoMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("MaBoMon");

                    b.HasIndex("MaKhoa");

                    b.ToTable("BoMons");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.DangKyLopHoc", b =>
                {
                    b.Property<string>("MaDangKy")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("DangKyLopHocs");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.DanhGia", b =>
                {
                    b.Property<string>("MaDanhGia")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungDanhGia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SoDiem")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.DiemDanh", b =>
                {
                    b.Property<string>("MaDiemDanh")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("NgayHoc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("MaDiemDanh");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("DiemDanhs");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.HocPhan", b =>
                {
                    b.Property<string>("MaHocPhan")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DiemDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("FileDeCuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HinhThucHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiHocPhan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaBaiGiang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaBaiTap")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaBoMon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MoTaChiTiet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTaNgan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SoLuongSinhVien")
                        .HasColumnType("int");

                    b.Property<int>("SoTiet")
                        .HasColumnType("int");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenHocPhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("MaHocPhan");

                    b.HasIndex("MaBaiGiang");

                    b.HasIndex("MaBaiTap");

                    b.HasIndex("MaBoMon");

                    b.HasIndex("MaGiangVien");

                    b.ToTable("HocPhans");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.Lop", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<string>("MaHocPhan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("NamHoc")
                        .HasColumnType("int");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiHoc")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TrangThaiLop")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaHocPhan");

                    b.ToTable("Lops");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.NguoiDung", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MSSV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaBoMon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaBoMon");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("MaQuyen");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.NopBaiTap", b =>
                {
                    b.Property<string>("MaNopBai")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FileNop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaBaiTap")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("MaNopBai");

                    b.HasIndex("MaBaiTap");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("NopBaiTaps");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.Quyen", b =>
                {
                    b.Property<string>("MaQuyen")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("MaQuyen");

                    b.ToTable("Quyens");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.ThongTinWeb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenWeb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ThongTinWebs");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.BaiGiang", b =>
                {
                    b.HasOne("WebBaiGiangAPI.Models.Lop", "Lop")
                        .WithMany("BaiGiangs")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.BaiTap", b =>
                {
                    b.HasOne("WebBaiGiangAPI.Models.Lop", "Lop")
                        .WithMany("BaiTaps")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBaiGiangAPI.Models.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.BangDiem", b =>
                {
                    b.HasOne("WebBaiGiangAPI.Models.Lop", "Lop")
                        .WithMany("BangDiems")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBaiGiangAPI.Models.NguoiDung", "SinhVien")
                        .WithMany("BangDiems")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.BoMon", b =>
                {
                    b.HasOne("WebBaiGiangAPI.Models.Khoa", "Khoa")
                        .WithMany("BoMons")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.DangKyLopHoc", b =>
                {
                    b.HasOne("WebBaiGiangAPI.Models.Lop", "Lop")
                        .WithMany("DangKyLopHocs")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBaiGiangAPI.Models.NguoiDung", "SinhVien")
                        .WithMany("DangKyLopHocs")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.DanhGia", b =>
                {
                    b.HasOne("WebBaiGiangAPI.Models.Lop", "Lop")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBaiGiangAPI.Models.NguoiDung", "SinhVien")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.DiemDanh", b =>
                {
                    b.HasOne("WebBaiGiangAPI.Models.Lop", "Lop")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBaiGiangAPI.Models.NguoiDung", "SinhVien")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.HocPhan", b =>
                {
                    b.HasOne("WebBaiGiangAPI.Models.BaiGiang", "BaiGiang")
                        .WithMany()
                        .HasForeignKey("MaBaiGiang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBaiGiangAPI.Models.BaiTap", "BaiTap")
                        .WithMany()
                        .HasForeignKey("MaBaiTap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBaiGiangAPI.Models.BoMon", "BoMon")
                        .WithMany("HocPhans")
                        .HasForeignKey("MaBoMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBaiGiangAPI.Models.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaiGiang");

                    b.Navigation("BaiTap");

                    b.Navigation("BoMon");

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.Lop", b =>
                {
                    b.HasOne("WebBaiGiangAPI.Models.HocPhan", "HocPhan")
                        .WithMany("Lops")
                        .HasForeignKey("MaHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocPhan");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.NguoiDung", b =>
                {
                    b.HasOne("WebBaiGiangAPI.Models.BoMon", "BoMon")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaBoMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBaiGiangAPI.Models.Khoa", "Khoa")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBaiGiangAPI.Models.Quyen", "Quyen")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoMon");

                    b.Navigation("Khoa");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.NopBaiTap", b =>
                {
                    b.HasOne("WebBaiGiangAPI.Models.BaiTap", "BaiTap")
                        .WithMany("NopBaiTaps")
                        .HasForeignKey("MaBaiTap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBaiGiangAPI.Models.NguoiDung", "SinhVien")
                        .WithMany("NopBaiTaps")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiTap");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.BaiTap", b =>
                {
                    b.Navigation("NopBaiTaps");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.BoMon", b =>
                {
                    b.Navigation("HocPhans");

                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.HocPhan", b =>
                {
                    b.Navigation("Lops");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.Khoa", b =>
                {
                    b.Navigation("BoMons");

                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.Lop", b =>
                {
                    b.Navigation("BaiGiangs");

                    b.Navigation("BaiTaps");

                    b.Navigation("BangDiems");

                    b.Navigation("DangKyLopHocs");

                    b.Navigation("DanhGias");

                    b.Navigation("DiemDanhs");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.NguoiDung", b =>
                {
                    b.Navigation("BangDiems");

                    b.Navigation("DangKyLopHocs");

                    b.Navigation("DanhGias");

                    b.Navigation("DiemDanhs");

                    b.Navigation("NopBaiTaps");
                });

            modelBuilder.Entity("WebBaiGiangAPI.Models.Quyen", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
